# Generated by Django 3.1.5 on 2021-02-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210213_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
