# Generated by Django 3.1.5 on 2021-02-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_todo_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='supply',
            name='amount',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='deliveryFrequency',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='supply',
            name='lastDelivery',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='nextDelivery',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='orderNumber',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='todo',
            name='lastDone',
            field=models.DateTimeField(blank=True),
        ),
    ]
