# Generated by Django 3.1.5 on 2021-02-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210213_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='recurring',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
