# Generated by Django 3.1.5 on 2021-02-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_todo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='lastDone',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
