# Generated by Django 3.1.7 on 2021-03-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20210213_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='deliveryFrequency',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='supply',
            name='lastDelivery',
            field=models.DateField(),
        ),
    ]
