# Generated by Django 3.1.7 on 2021-03-15 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20210311_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='lastDelivery',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supplier_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.supplier'),
        ),
    ]
