# Generated by Django 3.1.7 on 2021-03-15 22:48

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20210315_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
