# Generated by Django 3.1.7 on 2021-03-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_contact_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='messageSent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
