# Generated by Django 3.1.7 on 2021-03-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_todo_messagesent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='seeing',
            new_name='description',
        ),
    ]
