# Generated by Django 3.1.7 on 2021-03-22 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20210319_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['apptDate', 'apptTime']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='dateTime',
            new_name='apptDate',
        ),
        migrations.AddField(
            model_name='appointment',
            name='apptTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
