# Generated by Django 3.1.7 on 2021-03-26 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20210322_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todoDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='todoTime',
            field=models.TimeField(),
        ),
    ]
