# Generated by Django 3.1.7 on 2021-04-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20210326_1118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('name',)},
        ),
    ]
