# Generated by Django 3.1.7 on 2021-04-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20210420_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-apptDate', '-apptTime']},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['-lastDelivery']},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-todoDate', '-todoTime']},
        ),
        migrations.AlterField(
            model_name='supply',
            name='lastDelivery',
            field=models.DateField(),
        ),
    ]
